# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SKUDataFilterDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YYModel'
  # Pods for SKUDataFilterDemo

  target 'SKUDataFilterDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SKUDataFilterDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
